
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 2;
  public static final int GE = 40;
  public static final int SEMI = 9;
  public static final int INT = 12;
  public static final int FOR = 23;
  public static final int MINUS = 34;
  public static final int WRITE = 26;
  public static final int NOT = 45;
  public static final int AND = 37;
  public static final int LT = 41;
  public static final int RPAR = 4;
  public static final int NIL = 11;
  public static final int NOP = 17;
  public static final int OR = 38;
  public static final int BOOL = 13;
  public static final int COMMA = 10;
  public static final int DIV = 36;
  public static final int FLOAT_CONST = 31;
  public static final int PLUS = 33;
  public static final int ASSIGN = 16;
  public static final int IF = 20;
  public static final int ID = 6;
  public static final int LE = 42;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int INT_CONST = 30;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int GLOBAL = 8;
  public static final int EQ = 43;
  public static final int TIMES = 35;
  public static final int COLON = 7;
  public static final int ELSE = 22;
  public static final int READ = 25;
  public static final int WHILE = 18;
  public static final int FLOAT = 14;
  public static final int THEN = 21;
  public static final int NE = 44;
  public static final int END = 5;
  public static final int LPAR = 3;
  public static final int STRING = 15;
  public static final int LOCAL = 24;
  public static final int FALSE = 29;
  public static final int STRING_CONST = 32;
  public static final int GT = 39;
  public static final int DO = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUNCTION",
  "LPAR",
  "RPAR",
  "END",
  "ID",
  "COLON",
  "GLOBAL",
  "SEMI",
  "COMMA",
  "NIL",
  "INT",
  "BOOL",
  "FLOAT",
  "STRING",
  "ASSIGN",
  "NOP",
  "WHILE",
  "DO",
  "IF",
  "THEN",
  "ELSE",
  "FOR",
  "LOCAL",
  "READ",
  "WRITE",
  "RETURN",
  "TRUE",
  "FALSE",
  "INT_CONST",
  "FLOAT_CONST",
  "STRING_CONST",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "AND",
  "OR",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "NOT"
  };
}

